import React, { Fragment, useState, useEffect, useMemo } from 'react';
import { Accordion, List, TextareaItem, ImagePicker, Modal, Icon, Button, Checkbox } from 'antd-mobile';
import useSelections from '../hooks/useSelections';
import './index.less';
const AgreeItem = Checkbox.AgreeItem;
const CheckboxItem = Checkbox.CheckboxItem;

const ListItem = List.Item;
const prefixCls = 'select-multiple';
const h = React.createElement;
// import fetchApi from 'ehome-utils/lib/fetchApi';
/**
 * 多部门选择
 *
 */

function SdsjkflDSFSD() {
  return;
}
const SelectPartItem = function (props) {
  const { value = [], onChange = () => {} } = props;

  // const [valueList, setValueList] = useState([]);
  // const [orgList, setOrgList] = useState({
  //   id: 1,
  //   value: 1,
  //   name: 'name',
  //   childrens: [
  //     {
  //       id: 3,
  //       value: 3,
  //       name: 'name3',
  //       childrens: [
  //         { id: 5, value: 5, name: 'name5' },
  //         { id: 6, value: 6, name: 'name6' },
  //       ],
  //     },
  //     { id: 4, value: 4, name: 'name4' },
  //   ],
  // });
  const [orgList, setOrgList] = useState({
    namespaceId: 27830031,
    id: 2,
    parentId: 0,
    name: '测试企业1',
    path: '/2',
    level: 1,
    addressId: 0,
    organizationType: 'ENTERPRISE',
    status: 2,
    groupType: 'ENTERPRISE',
    directlyEnterpriseId: 0,
    orgNo: '2',
    createTime: 1626688421000,
    groupId: 2,
    selectedFlag: 1,
    childrens: [
      {
        namespaceId: 27830031,
        id: 9,
        parentId: 2,
        name: '天津市运行管理中心',
        path: '/2/9',
        level: 2,
        addressId: 0,
        organizationType: 'ENTERPRISE',
        status: 2,
        groupType: 'DEPARTMENT',
        directlyEnterpriseId: 2,
        orgNo: 'A001-120100000000',
        createTime: 1626760285000,
        showFlag: 1,
        selectedFlag: 1,
        childrens: [
          {
            namespaceId: 27830031,
            id: 11,
            parentId: 9,
            name: '南开区运行管理中心',
            path: '/2/9/11',
            level: 3,
            addressId: 0,
            organizationType: 'ENTERPRISE',
            status: 2,
            groupType: 'DEPARTMENT',
            directlyEnterpriseId: 2,
            orgNo: 'A001-120104000000',
            createTime: 1626760412000,
            showFlag: 1,
            selectedFlag: 1,
            childrens: [
              {
                namespaceId: 27830031,
                id: 17,
                parentId: 11,
                name: '长虹街道',
                path: '/2/9/11/17',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104001000',
                createTime: 1626760612000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 1,
                updateTime: 1626768938000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 20,
                parentId: 11,
                name: '鼓楼街道',
                path: '/2/9/11/20',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104002000',
                createTime: 1626760912000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 2,
                updateTime: 1626931990000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 22,
                parentId: 11,
                name: '兴南街道',
                path: '/2/9/11/22',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104003000',
                createTime: 1626761028000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 3,
                updateTime: 1626932001000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 26,
                parentId: 11,
                name: '广开街道',
                path: '/2/9/11/26',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104004000',
                createTime: 1626769609000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 4,
                updateTime: 1626932008000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 28,
                parentId: 11,
                name: '万兴街道',
                path: '/2/9/11/28',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104005000',
                createTime: 1626769824000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 5,
                updateTime: 1626932017000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 32,
                parentId: 11,
                name: '学府街道',
                path: '/2/9/11/32',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104006000',
                createTime: 1626769949000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 6,
                updateTime: 1626932025000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 36,
                parentId: 11,
                name: '向阳路街道',
                path: '/2/9/11/36',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104007000',
                createTime: 1626770492000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 7,
                updateTime: 1626932031000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 38,
                parentId: 11,
                name: '嘉陵道街道',
                path: '/2/9/11/38',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104008000',
                createTime: 1626770634000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 8,
                updateTime: 1626932037000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 40,
                parentId: 11,
                name: '王顶堤街道',
                path: '/2/9/11/40',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104009000',
                createTime: 1626770803000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 9,
                updateTime: 1626932047000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 42,
                parentId: 11,
                name: '水上公园街道',
                path: '/2/9/11/42',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104010000',
                createTime: 1626771259000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 10,
                updateTime: 1626932057000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 50,
                parentId: 11,
                name: '南开区城管委',
                path: '/2/9/11/50',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'B001-120104000000',
                createTime: 1627551794000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 11,
                updateTime: 1627552096000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
            ],
            managers: [],
            order: 1,
            updateTime: 1626768915000,
            creatorUid: 22,
            operatorUid: 22,
            setAdminFlag: 0,
          },
          {
            namespaceId: 27830031,
            id: 13,
            parentId: 9,
            name: '河西区运行管理中心',
            path: '/2/9/13',
            level: 3,
            addressId: 0,
            organizationType: 'ENTERPRISE',
            status: 2,
            groupType: 'DEPARTMENT',
            directlyEnterpriseId: 2,
            orgNo: 'A001-120103000000',
            createTime: 1626760457000,
            showFlag: 1,
            selectedFlag: 1,
            childrens: [],
            managers: [],
            order: 2,
            updateTime: 1626932070000,
            creatorUid: 22,
            operatorUid: 22,
            setAdminFlag: 0,
          },
          {
            namespaceId: 27830031,
            id: 15,
            parentId: 9,
            name: '和平区运行管理中心',
            path: '/2/9/15',
            level: 3,
            addressId: 0,
            organizationType: 'ENTERPRISE',
            status: 2,
            groupType: 'DEPARTMENT',
            directlyEnterpriseId: 2,
            orgNo: 'A001-120101000000',
            createTime: 1626760504000,
            showFlag: 1,
            selectedFlag: 1,
            childrens: [],
            managers: [],
            order: 3,
            updateTime: 1626932076000,
            creatorUid: 22,
            operatorUid: 22,
            setAdminFlag: 0,
          },
          {
            namespaceId: 27830031,
            id: 24,
            parentId: 9,
            name: '河东区运行管理中心',
            path: '/2/9/24',
            level: 3,
            addressId: 0,
            organizationType: 'ENTERPRISE',
            status: 2,
            groupType: 'DEPARTMENT',
            directlyEnterpriseId: 2,
            orgNo: 'A001-120102000000',
            createTime: 1626769553000,
            showFlag: 1,
            selectedFlag: 1,
            childrens: [],
            managers: [],
            order: 4,
            updateTime: 1626952080000,
            creatorUid: 22,
            operatorUid: 22,
            setAdminFlag: 0,
          },
          {
            namespaceId: 27830031,
            id: 34,
            parentId: 9,
            name: '河北区运行管理中心',
            path: '/2/9/34',
            level: 3,
            addressId: 0,
            organizationType: 'ENTERPRISE',
            status: 2,
            groupType: 'DEPARTMENT',
            directlyEnterpriseId: 2,
            orgNo: 'A001-120105000000',
            createTime: 1626770323000,
            showFlag: 1,
            selectedFlag: 1,
            childrens: [],
            managers: [],
            order: 5,
            updateTime: 1626932093000,
            creatorUid: 22,
            operatorUid: 22,
            setAdminFlag: 0,
          },
        ],
        managers: [],
        order: 1,
        updateTime: 1626942538000,
        creatorUid: 22,
        operatorUid: 22,
        setAdminFlag: 0,
      },
      {
        namespaceId: 27830031,
        id: 9,
        parentId: 2,
        name: '天津市运行管理中心',
        path: '/2/9',
        level: 2,
        addressId: 0,
        organizationType: 'ENTERPRISE',
        status: 2,
        groupType: 'DEPARTMENT',
        directlyEnterpriseId: 2,
        orgNo: 'A001-120100000000',
        createTime: 1626760285000,
        showFlag: 1,
        selectedFlag: 1,
        childrens: [
          {
            namespaceId: 27830031,
            id: 11,
            parentId: 9,
            name: '南开区运行管理中心',
            path: '/2/9/11',
            level: 3,
            addressId: 0,
            organizationType: 'ENTERPRISE',
            status: 2,
            groupType: 'DEPARTMENT',
            directlyEnterpriseId: 2,
            orgNo: 'A001-120104000000',
            createTime: 1626760412000,
            showFlag: 1,
            selectedFlag: 1,
            childrens: [
              {
                namespaceId: 27830031,
                id: 17,
                parentId: 11,
                name: '长虹街道',
                path: '/2/9/11/17',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104001000',
                createTime: 1626760612000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 1,
                updateTime: 1626768938000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 20,
                parentId: 11,
                name: '鼓楼街道',
                path: '/2/9/11/20',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104002000',
                createTime: 1626760912000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 2,
                updateTime: 1626931990000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 22,
                parentId: 11,
                name: '兴南街道',
                path: '/2/9/11/22',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104003000',
                createTime: 1626761028000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 3,
                updateTime: 1626932001000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 26,
                parentId: 11,
                name: '广开街道',
                path: '/2/9/11/26',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104004000',
                createTime: 1626769609000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 4,
                updateTime: 1626932008000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 28,
                parentId: 11,
                name: '万兴街道',
                path: '/2/9/11/28',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104005000',
                createTime: 1626769824000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 5,
                updateTime: 1626932017000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 32,
                parentId: 11,
                name: '学府街道',
                path: '/2/9/11/32',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104006000',
                createTime: 1626769949000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 6,
                updateTime: 1626932025000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 36,
                parentId: 11,
                name: '向阳路街道',
                path: '/2/9/11/36',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104007000',
                createTime: 1626770492000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 7,
                updateTime: 1626932031000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 38,
                parentId: 11,
                name: '嘉陵道街道',
                path: '/2/9/11/38',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104008000',
                createTime: 1626770634000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 8,
                updateTime: 1626932037000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 40,
                parentId: 11,
                name: '王顶堤街道',
                path: '/2/9/11/40',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104009000',
                createTime: 1626770803000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 9,
                updateTime: 1626932047000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 42,
                parentId: 11,
                name: '水上公园街道',
                path: '/2/9/11/42',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104010000',
                createTime: 1626771259000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 10,
                updateTime: 1626932057000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 50,
                parentId: 11,
                name: '南开区城管委',
                path: '/2/9/11/50',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'B001-120104000000',
                createTime: 1627551794000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 11,
                updateTime: 1627552096000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
            ],
            managers: [],
            order: 1,
            updateTime: 1626768915000,
            creatorUid: 22,
            operatorUid: 22,
            setAdminFlag: 0,
          },
          {
            namespaceId: 27830031,
            id: 13,
            parentId: 9,
            name: '河西区运行管理中心',
            path: '/2/9/13',
            level: 3,
            addressId: 0,
            organizationType: 'ENTERPRISE',
            status: 2,
            groupType: 'DEPARTMENT',
            directlyEnterpriseId: 2,
            orgNo: 'A001-120103000000',
            createTime: 1626760457000,
            showFlag: 1,
            selectedFlag: 1,
            childrens: [],
            managers: [],
            order: 2,
            updateTime: 1626932070000,
            creatorUid: 22,
            operatorUid: 22,
            setAdminFlag: 0,
            childrens: [
              {
                namespaceId: 27830031,
                id: 17,
                parentId: 11,
                name: '长虹街道',
                path: '/2/9/11/17',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104001000',
                createTime: 1626760612000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 1,
                updateTime: 1626768938000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 20,
                parentId: 11,
                name: '鼓楼街道',
                path: '/2/9/11/20',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104002000',
                createTime: 1626760912000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 2,
                updateTime: 1626931990000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 22,
                parentId: 11,
                name: '兴南街道',
                path: '/2/9/11/22',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104003000',
                createTime: 1626761028000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 3,
                updateTime: 1626932001000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 26,
                parentId: 11,
                name: '广开街道',
                path: '/2/9/11/26',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104004000',
                createTime: 1626769609000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 4,
                updateTime: 1626932008000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 28,
                parentId: 11,
                name: '万兴街道',
                path: '/2/9/11/28',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104005000',
                createTime: 1626769824000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 5,
                updateTime: 1626932017000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 32,
                parentId: 11,
                name: '学府街道',
                path: '/2/9/11/32',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104006000',
                createTime: 1626769949000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 6,
                updateTime: 1626932025000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 36,
                parentId: 11,
                name: '向阳路街道',
                path: '/2/9/11/36',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104007000',
                createTime: 1626770492000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 7,
                updateTime: 1626932031000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 38,
                parentId: 11,
                name: '嘉陵道街道',
                path: '/2/9/11/38',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104008000',
                createTime: 1626770634000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 8,
                updateTime: 1626932037000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 40,
                parentId: 11,
                name: '王顶堤街道',
                path: '/2/9/11/40',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104009000',
                createTime: 1626770803000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 9,
                updateTime: 1626932047000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 42,
                parentId: 11,
                name: '水上公园街道',
                path: '/2/9/11/42',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'A001-120104010000',
                createTime: 1626771259000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 10,
                updateTime: 1626932057000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
              {
                namespaceId: 27830031,
                id: 50,
                parentId: 11,
                name: '南开区城管委',
                path: '/2/9/11/50',
                level: 4,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: 'B001-120104000000',
                createTime: 1627551794000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 11,
                updateTime: 1627552096000,
                creatorUid: 22,
                operatorUid: 22,
                setAdminFlag: 0,
              },
            ],
          },
          {
            namespaceId: 27830031,
            id: 15,
            parentId: 9,
            name: '和平区运行管理中心',
            path: '/2/9/15',
            level: 3,
            addressId: 0,
            organizationType: 'ENTERPRISE',
            status: 2,
            groupType: 'DEPARTMENT',
            directlyEnterpriseId: 2,
            orgNo: 'A001-120101000000',
            createTime: 1626760504000,
            showFlag: 1,
            selectedFlag: 1,
            childrens: [],
            managers: [],
            order: 3,
            updateTime: 1626932076000,
            creatorUid: 22,
            operatorUid: 22,
            setAdminFlag: 0,
          },
          {
            namespaceId: 27830031,
            id: 24,
            parentId: 9,
            name: '河东区运行管理中心',
            path: '/2/9/24',
            level: 3,
            addressId: 0,
            organizationType: 'ENTERPRISE',
            status: 2,
            groupType: 'DEPARTMENT',
            directlyEnterpriseId: 2,
            orgNo: 'A001-120102000000',
            createTime: 1626769553000,
            showFlag: 1,
            selectedFlag: 1,
            childrens: [],
            managers: [],
            order: 4,
            updateTime: 1626952080000,
            creatorUid: 22,
            operatorUid: 22,
            setAdminFlag: 0,
          },
          {
            namespaceId: 27830031,
            id: 34,
            parentId: 9,
            name: '河北区运行管理中心',
            path: '/2/9/34',
            level: 3,
            addressId: 0,
            organizationType: 'ENTERPRISE',
            status: 2,
            groupType: 'DEPARTMENT',
            directlyEnterpriseId: 2,
            orgNo: 'A001-120105000000',
            createTime: 1626770323000,
            showFlag: 1,
            selectedFlag: 1,
            childrens: [],
            managers: [],
            order: 5,
            updateTime: 1626932093000,
            creatorUid: 22,
            operatorUid: 22,
            setAdminFlag: 0,
          },
        ],
        managers: [],
        order: 1,
        updateTime: 1626942538000,
        creatorUid: 22,
        operatorUid: 22,
        setAdminFlag: 0,
      },

      {
        namespaceId: 27830031,
        id: 44,
        parentId: 2,
        name: '测试公司',
        path: '/2/44',
        level: 2,
        addressId: 0,
        organizationType: 'ENTERPRISE',
        status: 2,
        groupType: 'ENTERPRISE',
        directlyEnterpriseId: 2,
        orgNo: '1111111111',
        createTime: 1626916209000,
        showFlag: 1,
        selectedFlag: 1,
        childrens: [
          {
            namespaceId: 27830031,
            id: 46,
            parentId: 44,
            name: '测试A部门',
            path: '/2/44/46',
            level: 3,
            addressId: 0,
            organizationType: 'ENTERPRISE',
            status: 2,
            groupType: 'DEPARTMENT',
            directlyEnterpriseId: 44,
            orgNo: '123456789',
            createTime: 1626916225000,
            showFlag: 1,
            selectedFlag: 1,
            childrens: [],
            managers: [],
            order: 1,
            updateTime: 1626916225000,
            creatorUid: 22,
            setAdminFlag: 0,
          },
        ],
        managers: [],
        order: 2,
        updateTime: 1626916209000,
        creatorUid: 22,
        setAdminFlag: 0,
      },
      {
        namespaceId: 27830031,
        id: 48,
        parentId: 2,
        name: '软件部',
        path: '/2/48',
        level: 2,
        addressId: 0,
        organizationType: 'ENTERPRISE',
        status: 2,
        groupType: 'DEPARTMENT',
        directlyEnterpriseId: 2,
        orgNo: '48',
        createTime: 1627018391000,
        showFlag: 1,
        selectedFlag: 1,
        childrens: [],
        managers: [],
        order: 3,
        updateTime: 1627018391000,
        creatorUid: 22,
        setAdminFlag: 0,
      },
    ],
    updateTime: 1626688424000,
    setAdminFlag: 1,
    workPlatformFlag: 1,
    sourceType: 'ENTERPRISE',
  });
  const flatOrg = useMemo(() => {
    const flat = [];
    function djhsklfdsjh(item) {
      if (item.childrens && item.childrens.length > 0) {
        flat.push(item);
        item.childrens.forEach(item => {
          djhsklfdsjh(item);
        });
      } else {
        flat.push(item);
      }
    }
    djhsklfdsjh(orgList);
    return flat;
  }, [orgList]);
  console.log('🚀 ~ flatOrg ~ flatOrg', flatOrg);

  const {
    selected,
    setSelected,
    allSelected,
    isSelected,
    toggle,
    toggleAll,
    partiallySelected,
    selectAll,
    unSelectAll,
  } = useSelections(flatOrg, []);
  console.log('🚀 ~ SelectPartItem ~ selected', selected);

  // useEffect(() => {
  //   const organizationId = sessionStorage.getItem("organizationId");

  //   fetchApi({
  //     api: "/coorprocessingchangshuai/baseManager/org/queryChildrenOrg",
  //     data: {
  //       namespaceId: 27830031,
  //       organizationId,
  //       appId: 386,
  //     },
  //   }).then((res) => {
  //     console.log(res);
  //   });
  // }, []);
  const [checkItemList, setCheckItemList] = useState([
    { value: 0, label: 'Ph.D.', check: false },
    { value: 1, label: 'Bachelor', check: false },
    { value: 2, label: 'College diploma', check: false },
  ]);
  const [visible, setVisible] = useState(false);

  const onCheckChange = (checkValue, index) => {
    //选中列表
    const currentValueList = [...value];

    //当前选中的项目
    const currentValue = { ...checkValue };
    currentValue.check = !currentValue.check;

    checkItemList[index] = currentValue;
    setCheckItemList(checkItemList => {
      const reliableCheckItemList = [...checkItemList];
      reliableCheckItemList[index] = currentValue;
      return reliableCheckItemList;
    });

    // onChange([...checkItemList]);
    // let currentValue = [...value];
    // const valueIndex = value.indexOf(checkValue);
    // console.log("🚀 ~ onCheckChange ~ valueIndex", valueIndex);
    // //在数组中是取消,不在数组中是选择
    // if (valueIndex !== -1) {
    //   currentValue.splice(valueIndex, 1);
    // } else {
    //   currentValue.push(checkValue);
    // }
    // console.log("🚀 ~ onCheckChange ~ currentValue", currentValue);
    // onChange(currentValue);
  };

  const onAccordionChange = key => {
    console.log('🚀 ~ constonAccordionChange ~ key', key);
  };

  //计算当前check为true的值并传出
  useEffect(() => {
    onChange(checkItemList.filter(item => item.check));
  }, [checkItemList]);
  const startLevel = 2;

  const AccordionItem = props => {
    const { item } = props;
    return (
      <div
        onClick={e => {
          e.preventDefault();
        }}
        style={{
          display: 'inline-block',
          paddingLeft: `${((item.level - startLevel) * 40) / 100}rem`,
        }}>
        {/* <CheckboxItem></CheckboxItem> */}
        <AgreeItem
          // checked={true}
          checked={isSelected(item)}
          onChange={e => {
            console.log('checkbox', e);
          }}
          onClick={e => {
            // unSelectAll();
            unSelectAll();
            toggle(item);

            // unSelectAll();
            e.stopPropagation();
          }}>
          {item.name}
        </AgreeItem>
      </div>
    );
  };
  const genAccordion = list => {
    const content = list.map((item, index) => {
      if (item.childrens && item.childrens.length > 0) {
        return (
          <Accordion.Panel
            key={index}
            className="test-acc-panel"
            // header={<AccordionItem item={item}></AccordionItem>}
            header={item.name}>
            {genAccordion(item.childrens)}
          </Accordion.Panel>
        );
      } else {
        return h(
          props => {
            return (
              <List className="test-list" key={index}>
                <List.Item className="test-list-item" key={index}>
                  <AccordionItem item={item}></AccordionItem>
                </List.Item>
              </List>
            );
          },
          {
            key: index,
          }
        );
      }
    });
    return <Accordion>{content}</Accordion>;
  };

  return (
    <Fragment>
      <div className={prefixCls}>
        <ListItem
          arrow="horizontal"
          align="top"
          onClick={() => {
            setVisible(true);
          }}>
          <div style={{ marginBottom: value.length > 0 ? '30px' : '' }}>派遣给 :</div>
          <div>
            {value.map(item => {
              return <div key={item.value}>{item.label}</div>;
            })}
          </div>
        </ListItem>
        <button
          onClick={() => {
            unSelectAll();
          }}>
          点击
        </button>
        <button
          onClick={() => {
            // allSelected
            setSelected([
              {
                namespaceId: 27830031,
                id: 48,
                parentId: 2,
                name: '软件部',
                path: '/2/48',
                level: 2,
                addressId: 0,
                organizationType: 'ENTERPRISE',
                status: 2,
                groupType: 'DEPARTMENT',
                directlyEnterpriseId: 2,
                orgNo: '48',
                createTime: 1627018391000,
                showFlag: 1,
                selectedFlag: 1,
                childrens: [],
                managers: [],
                order: 3,
                updateTime: 1627018391000,
                creatorUid: 22,
                setAdminFlag: 0,
              },
            ]);
          }}>
          点击
        </button>
        <Modal popup visible={visible} onClose={() => setVisible(false)} animationType="slide-down">
          <div className={`${prefixCls}-modal__content`}>
            {genAccordion([orgList])}
            <Button></Button>
          </div>
        </Modal>
      </div>

      {/* <Modal popup visible={visible} onClose={() => setVisible(false)} animationType="slide-up">
        <List className="popup-list" className={`${prefixCls}-select-part-modal__content`}>
          {checkItemList.map((item, index) => (
            <CheckboxItem key={index} value={item} checked={item.check} onChange={() => onCheckChange(item, index)}>
              {item.label}
            </CheckboxItem>
          ))}
        </List>
      </Modal> */}
    </Fragment>
  );
};
export default SelectPartItem;
